CREATE TABLE IF NOT EXISTS market_data (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume BIGINT,
    UNIQUE (timestamp, ticker)
);

CREATE INDEX IF NOT EXISTS idx_market_data_ts ON market_data (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_market_data_ticker_ts ON market_data (ticker, timestamp DESC);

COMMENT ON TABLE market_data IS 'Daily OHLCV data for all tickers (DXY, forex, VIX, SP500). Owner: pipeline@project-akhir-ipbd';
COMMENT ON COLUMN market_data.ticker IS 'Ticker symbol (DX-Y.NYB, EURUSD=X, etc.)';
COMMENT ON COLUMN market_data.timestamp IS 'UTC timestamp of the daily bar';
COMMENT ON COLUMN market_data.close IS 'Closing price of the daily bar';

CREATE TABLE IF NOT EXISTS predictions (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    predicted_close DOUBLE PRECISION NOT NULL,
    actual_close DOUBLE PRECISION,
    pred_price_1m DOUBLE PRECISION,
    pred_price_3m DOUBLE PRECISION,
    pred_price_5m DOUBLE PRECISION,
    pred_price_30m DOUBLE PRECISION,
    dxy_close DOUBLE PRECISION,
    features JSONB
);

CREATE INDEX IF NOT EXISTS idx_predictions_ts ON predictions (timestamp DESC);

COMMENT ON TABLE predictions IS 'Volatility and price predictions generated by the ML pipeline. Owner: pipeline@project-akhir-ipbd';
COMMENT ON COLUMN predictions.predicted_close IS 'Predicted volatility (rolling std dev of DXY returns)';
COMMENT ON COLUMN predictions.actual_close IS 'Actual volatility (ground truth)';
COMMENT ON COLUMN predictions.pred_price_1m IS 'Predicted DXY price 1 minute ahead';
COMMENT ON COLUMN predictions.pred_price_3m IS 'Predicted DXY price 3 minutes ahead';
COMMENT ON COLUMN predictions.pred_price_5m IS 'Predicted DXY price 5 minutes ahead';
COMMENT ON COLUMN predictions.pred_price_30m IS 'Predicted DXY price 30 minutes ahead';
COMMENT ON COLUMN predictions.features IS 'Feature vector snapshot used for the prediction (JSON)';

CREATE TABLE IF NOT EXISTS intraday_bars (
    ticker VARCHAR(10) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume BIGINT,
    PRIMARY KEY (ticker, timestamp)
);

COMMENT ON TABLE intraday_bars IS '1-minute OHLCV bars for all tickers. Used for training and feature computation. Owner: pipeline@project-akhir-ipbd';
COMMENT ON COLUMN intraday_bars.ticker IS 'Ticker symbol';
COMMENT ON COLUMN intraday_bars.timestamp IS 'UTC open time of the 1-minute bar';
COMMENT ON COLUMN intraday_bars.close IS 'Close price of the 1-minute bar';

ALTER TABLE predictions ADD COLUMN IF NOT EXISTS pred_price_30m DOUBLE PRECISION;
ALTER TABLE predictions ADD COLUMN IF NOT EXISTS source VARCHAR(20);
ALTER TABLE predictions ADD COLUMN IF NOT EXISTS dxy_close DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS batch_metrics (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    predicted_vol DOUBLE PRECISION,
    actual_vol DOUBLE PRECISION,
    success BOOLEAN,
    error_message TEXT
);
COMMENT ON TABLE batch_metrics IS 'Batch predictor cycle results. Used for monitoring in Grafana.';

CREATE TABLE IF NOT EXISTS dbt_test_results (
    id SERIAL PRIMARY KEY,
    run_at TIMESTAMPTZ DEFAULT NOW(),
    models_found INTEGER,
    tests_total INTEGER,
    passed INTEGER,
    warnings INTEGER,
    errors INTEGER,
    skipped INTEGER,
    duration_seconds DOUBLE PRECISION,
    success BOOLEAN,
    raw_output TEXT
);

COMMENT ON TABLE dbt_test_results IS 'dbt test run history. Used for data quality monitoring in Grafana. Owner: pipeline@project-akhir-ipbd';
